server:
  tomcat:
    max-threads: 8
management:
    contextPath: /management
    add-application-context-header: false
    health:
        db.enabled: false
        diskspace.enabled: false
    security.enabled: false

endpoints:
    health.mapping.DOWN: OK
    health.mapping.OUT_OF_SERVICE : OK

git-hub_endpoints:
  search-repo-by-owner: https://api.github.com/repos/{owner}/{repo}